// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// AccountGroup is the predicate function for accountgroup builders.
type AccountGroup func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// UsageLog is the predicate function for usagelog builders.
type UsageLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
