// Code generated by ent, DO NOT EDIT.

package usagelog

import (
	"cmd2api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAPIKeyID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAccountID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldGroupID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRequestID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldModel, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUpstreamModel, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputTokens, v))
}

// CacheCreationTokens applies equality check predicate on the "cache_creation_tokens" field. It's identical to CacheCreationTokensEQ.
func CacheCreationTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheReadTokens applies equality check predicate on the "cache_read_tokens" field. It's identical to CacheReadTokensEQ.
func CacheReadTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheReadTokens, v))
}

// InputCost applies equality check predicate on the "input_cost" field. It's identical to InputCostEQ.
func InputCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputCost, v))
}

// OutputCost applies equality check predicate on the "output_cost" field. It's identical to OutputCostEQ.
func OutputCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputCost, v))
}

// TotalCost applies equality check predicate on the "total_cost" field. It's identical to TotalCostEQ.
func TotalCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldTotalCost, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRateMultiplier, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldStream, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldDurationMs, v))
}

// FirstTokenMs applies equality check predicate on the "first_token_ms" field. It's identical to FirstTokenMsEQ.
func FirstTokenMs(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldFirstTokenMs, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldStatusCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldErrorMessage, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserAgent, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldIPAddress, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldUserID, vs...))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldAccountID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldGroupID))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldRequestID, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldModel, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelIsNil applies the IsNil predicate on the "upstream_model" field.
func UpstreamModelIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldUpstreamModel))
}

// UpstreamModelNotNil applies the NotNil predicate on the "upstream_model" field.
func UpstreamModelNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldUpstreamModel))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldOutputTokens, v))
}

// CacheCreationTokensEQ applies the EQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensNEQ applies the NEQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensIn applies the In predicate on the "cache_creation_tokens" field.
func CacheCreationTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensNotIn applies the NotIn predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensGT applies the GT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensGTE applies the GTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLT applies the LT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLTE applies the LTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheCreationTokens, v))
}

// CacheReadTokensEQ applies the EQ predicate on the "cache_read_tokens" field.
func CacheReadTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensNEQ applies the NEQ predicate on the "cache_read_tokens" field.
func CacheReadTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensIn applies the In predicate on the "cache_read_tokens" field.
func CacheReadTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensNotIn applies the NotIn predicate on the "cache_read_tokens" field.
func CacheReadTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensGT applies the GT predicate on the "cache_read_tokens" field.
func CacheReadTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheReadTokens, v))
}

// CacheReadTokensGTE applies the GTE predicate on the "cache_read_tokens" field.
func CacheReadTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheReadTokens, v))
}

// CacheReadTokensLT applies the LT predicate on the "cache_read_tokens" field.
func CacheReadTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheReadTokens, v))
}

// CacheReadTokensLTE applies the LTE predicate on the "cache_read_tokens" field.
func CacheReadTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheReadTokens, v))
}

// InputCostEQ applies the EQ predicate on the "input_cost" field.
func InputCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputCost, v))
}

// InputCostNEQ applies the NEQ predicate on the "input_cost" field.
func InputCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldInputCost, v))
}

// InputCostIn applies the In predicate on the "input_cost" field.
func InputCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldInputCost, vs...))
}

// InputCostNotIn applies the NotIn predicate on the "input_cost" field.
func InputCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldInputCost, vs...))
}

// InputCostGT applies the GT predicate on the "input_cost" field.
func InputCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldInputCost, v))
}

// InputCostGTE applies the GTE predicate on the "input_cost" field.
func InputCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldInputCost, v))
}

// InputCostLT applies the LT predicate on the "input_cost" field.
func InputCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldInputCost, v))
}

// InputCostLTE applies the LTE predicate on the "input_cost" field.
func InputCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldInputCost, v))
}

// OutputCostEQ applies the EQ predicate on the "output_cost" field.
func OutputCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputCost, v))
}

// OutputCostNEQ applies the NEQ predicate on the "output_cost" field.
func OutputCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldOutputCost, v))
}

// OutputCostIn applies the In predicate on the "output_cost" field.
func OutputCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldOutputCost, vs...))
}

// OutputCostNotIn applies the NotIn predicate on the "output_cost" field.
func OutputCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldOutputCost, vs...))
}

// OutputCostGT applies the GT predicate on the "output_cost" field.
func OutputCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldOutputCost, v))
}

// OutputCostGTE applies the GTE predicate on the "output_cost" field.
func OutputCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldOutputCost, v))
}

// OutputCostLT applies the LT predicate on the "output_cost" field.
func OutputCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldOutputCost, v))
}

// OutputCostLTE applies the LTE predicate on the "output_cost" field.
func OutputCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldOutputCost, v))
}

// TotalCostEQ applies the EQ predicate on the "total_cost" field.
func TotalCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldTotalCost, v))
}

// TotalCostNEQ applies the NEQ predicate on the "total_cost" field.
func TotalCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldTotalCost, v))
}

// TotalCostIn applies the In predicate on the "total_cost" field.
func TotalCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldTotalCost, vs...))
}

// TotalCostNotIn applies the NotIn predicate on the "total_cost" field.
func TotalCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldTotalCost, vs...))
}

// TotalCostGT applies the GT predicate on the "total_cost" field.
func TotalCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldTotalCost, v))
}

// TotalCostGTE applies the GTE predicate on the "total_cost" field.
func TotalCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldTotalCost, v))
}

// TotalCostLT applies the LT predicate on the "total_cost" field.
func TotalCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldTotalCost, v))
}

// TotalCostLTE applies the LTE predicate on the "total_cost" field.
func TotalCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldTotalCost, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldRateMultiplier, v))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldStream, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldDurationMs))
}

// FirstTokenMsEQ applies the EQ predicate on the "first_token_ms" field.
func FirstTokenMsEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldFirstTokenMs, v))
}

// FirstTokenMsNEQ applies the NEQ predicate on the "first_token_ms" field.
func FirstTokenMsNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldFirstTokenMs, v))
}

// FirstTokenMsIn applies the In predicate on the "first_token_ms" field.
func FirstTokenMsIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldFirstTokenMs, vs...))
}

// FirstTokenMsNotIn applies the NotIn predicate on the "first_token_ms" field.
func FirstTokenMsNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldFirstTokenMs, vs...))
}

// FirstTokenMsGT applies the GT predicate on the "first_token_ms" field.
func FirstTokenMsGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldFirstTokenMs, v))
}

// FirstTokenMsGTE applies the GTE predicate on the "first_token_ms" field.
func FirstTokenMsGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldFirstTokenMs, v))
}

// FirstTokenMsLT applies the LT predicate on the "first_token_ms" field.
func FirstTokenMsLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldFirstTokenMs, v))
}

// FirstTokenMsLTE applies the LTE predicate on the "first_token_ms" field.
func FirstTokenMsLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldFirstTokenMs, v))
}

// FirstTokenMsIsNil applies the IsNil predicate on the "first_token_ms" field.
func FirstTokenMsIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldFirstTokenMs))
}

// FirstTokenMsNotNil applies the NotNil predicate on the "first_token_ms" field.
func FirstTokenMsNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldFirstTokenMs))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldStatusCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldUserAgent, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressIsNil applies the IsNil predicate on the "ip_address" field.
func IPAddressIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldIPAddress))
}

// IPAddressNotNil applies the NotNil predicate on the "ip_address" field.
func IPAddressNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldIPAddress))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldIPAddress, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageLog) predicate.UsageLog {
	return predicate.UsageLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageLog) predicate.UsageLog {
	return predicate.UsageLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageLog) predicate.UsageLog {
	return predicate.UsageLog(sql.NotPredicates(p))
}
