// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cmd2api/ent/account"
	"cmd2api/ent/accountgroup"
	"cmd2api/ent/apikey"
	"cmd2api/ent/group"
	"cmd2api/ent/schema"
	"cmd2api/ent/usagelog"
	"cmd2api/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyMixin := schema.APIKey{}.Mixin()
	apikeyMixinFields0 := apikeyMixin[0].Fields()
	_ = apikeyMixinFields0
	apikeyFields := schema.APIKey{}.Fields()
	_ = apikeyFields
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyMixinFields0[0].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	// apikeyDescUpdatedAt is the schema descriptor for updated_at field.
	apikeyDescUpdatedAt := apikeyMixinFields0[1].Descriptor()
	// apikey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apikey.DefaultUpdatedAt = apikeyDescUpdatedAt.Default.(func() time.Time)
	// apikey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apikey.UpdateDefaultUpdatedAt = apikeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apikeyDescKey is the schema descriptor for key field.
	apikeyDescKey := apikeyFields[1].Descriptor()
	// apikey.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	apikey.KeyValidator = func() func(string) error {
		validators := apikeyDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// apikeyDescName is the schema descriptor for name field.
	apikeyDescName := apikeyFields[2].Descriptor()
	// apikey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apikey.NameValidator = func() func(string) error {
		validators := apikeyDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// apikeyDescStatus is the schema descriptor for status field.
	apikeyDescStatus := apikeyFields[4].Descriptor()
	// apikey.DefaultStatus holds the default value on creation for the status field.
	apikey.DefaultStatus = apikeyDescStatus.Default.(string)
	// apikey.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	apikey.StatusValidator = apikeyDescStatus.Validators[0].(func(string) error)
	// apikeyDescQuota is the schema descriptor for quota field.
	apikeyDescQuota := apikeyFields[7].Descriptor()
	// apikey.DefaultQuota holds the default value on creation for the quota field.
	apikey.DefaultQuota = apikeyDescQuota.Default.(float64)
	// apikeyDescQuotaUsed is the schema descriptor for quota_used field.
	apikeyDescQuotaUsed := apikeyFields[8].Descriptor()
	// apikey.DefaultQuotaUsed holds the default value on creation for the quota_used field.
	apikey.DefaultQuotaUsed = apikeyDescQuotaUsed.Default.(float64)
	accountMixin := schema.Account{}.Mixin()
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountMixinFields0[0].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountMixinFields0[1].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[0].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = func() func(string) error {
		validators := accountDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescPlatform is the schema descriptor for platform field.
	accountDescPlatform := accountFields[2].Descriptor()
	// account.DefaultPlatform holds the default value on creation for the platform field.
	account.DefaultPlatform = accountDescPlatform.Default.(string)
	// account.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	account.PlatformValidator = func() func(string) error {
		validators := accountDescPlatform.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(platform string) error {
			for _, fn := range fns {
				if err := fn(platform); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescType is the schema descriptor for type field.
	accountDescType := accountFields[3].Descriptor()
	// account.DefaultType holds the default value on creation for the type field.
	account.DefaultType = accountDescType.Default.(string)
	// account.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	account.TypeValidator = func() func(string) error {
		validators := accountDescType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_type string) error {
			for _, fn := range fns {
				if err := fn(_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescCredentials is the schema descriptor for credentials field.
	accountDescCredentials := accountFields[4].Descriptor()
	// account.DefaultCredentials holds the default value on creation for the credentials field.
	account.DefaultCredentials = accountDescCredentials.Default.(func() map[string]interface{})
	// accountDescExtra is the schema descriptor for extra field.
	accountDescExtra := accountFields[5].Descriptor()
	// account.DefaultExtra holds the default value on creation for the extra field.
	account.DefaultExtra = accountDescExtra.Default.(func() map[string]interface{})
	// accountDescConcurrency is the schema descriptor for concurrency field.
	accountDescConcurrency := accountFields[6].Descriptor()
	// account.DefaultConcurrency holds the default value on creation for the concurrency field.
	account.DefaultConcurrency = accountDescConcurrency.Default.(int)
	// accountDescPriority is the schema descriptor for priority field.
	accountDescPriority := accountFields[7].Descriptor()
	// account.DefaultPriority holds the default value on creation for the priority field.
	account.DefaultPriority = accountDescPriority.Default.(int)
	// accountDescRateMultiplier is the schema descriptor for rate_multiplier field.
	accountDescRateMultiplier := accountFields[8].Descriptor()
	// account.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	account.DefaultRateMultiplier = accountDescRateMultiplier.Default.(float64)
	// accountDescStatus is the schema descriptor for status field.
	accountDescStatus := accountFields[9].Descriptor()
	// account.DefaultStatus holds the default value on creation for the status field.
	account.DefaultStatus = accountDescStatus.Default.(string)
	// account.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	account.StatusValidator = accountDescStatus.Validators[0].(func(string) error)
	// accountDescSchedulable is the schema descriptor for schedulable field.
	accountDescSchedulable := accountFields[13].Descriptor()
	// account.DefaultSchedulable holds the default value on creation for the schedulable field.
	account.DefaultSchedulable = accountDescSchedulable.Default.(bool)
	// accountDescBalancePlanID is the schema descriptor for balance_plan_id field.
	accountDescBalancePlanID := accountFields[20].Descriptor()
	// account.BalancePlanIDValidator is a validator for the "balance_plan_id" field. It is called by the builders before save.
	account.BalancePlanIDValidator = accountDescBalancePlanID.Validators[0].(func(string) error)
	// accountDescConsecutiveFailures is the schema descriptor for consecutive_failures field.
	accountDescConsecutiveFailures := accountFields[28].Descriptor()
	// account.DefaultConsecutiveFailures holds the default value on creation for the consecutive_failures field.
	account.DefaultConsecutiveFailures = accountDescConsecutiveFailures.Default.(int)
	// accountDescLastHealthCheckOk is the schema descriptor for last_health_check_ok field.
	accountDescLastHealthCheckOk := accountFields[30].Descriptor()
	// account.DefaultLastHealthCheckOk holds the default value on creation for the last_health_check_ok field.
	account.DefaultLastHealthCheckOk = accountDescLastHealthCheckOk.Default.(bool)
	accountgroupFields := schema.AccountGroup{}.Fields()
	_ = accountgroupFields
	// accountgroupDescPriority is the schema descriptor for priority field.
	accountgroupDescPriority := accountgroupFields[2].Descriptor()
	// accountgroup.DefaultPriority holds the default value on creation for the priority field.
	accountgroup.DefaultPriority = accountgroupDescPriority.Default.(int)
	// accountgroupDescCreatedAt is the schema descriptor for created_at field.
	accountgroupDescCreatedAt := accountgroupFields[3].Descriptor()
	// accountgroup.DefaultCreatedAt holds the default value on creation for the created_at field.
	accountgroup.DefaultCreatedAt = accountgroupDescCreatedAt.Default.(func() time.Time)
	groupMixin := schema.Group{}.Mixin()
	groupMixinFields0 := groupMixin[0].Fields()
	_ = groupMixinFields0
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupMixinFields0[0].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupMixinFields0[1].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = func() func(string) error {
		validators := groupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescDescription is the schema descriptor for description field.
	groupDescDescription := groupFields[1].Descriptor()
	// group.DefaultDescription holds the default value on creation for the description field.
	group.DefaultDescription = groupDescDescription.Default.(string)
	// groupDescPlatform is the schema descriptor for platform field.
	groupDescPlatform := groupFields[2].Descriptor()
	// group.DefaultPlatform holds the default value on creation for the platform field.
	group.DefaultPlatform = groupDescPlatform.Default.(string)
	// group.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	group.PlatformValidator = func() func(string) error {
		validators := groupDescPlatform.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(platform string) error {
			for _, fn := range fns {
				if err := fn(platform); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescRateMultiplier is the schema descriptor for rate_multiplier field.
	groupDescRateMultiplier := groupFields[3].Descriptor()
	// group.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	group.DefaultRateMultiplier = groupDescRateMultiplier.Default.(float64)
	// groupDescStatus is the schema descriptor for status field.
	groupDescStatus := groupFields[4].Descriptor()
	// group.DefaultStatus holds the default value on creation for the status field.
	group.DefaultStatus = groupDescStatus.Default.(string)
	// group.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	group.StatusValidator = groupDescStatus.Validators[0].(func(string) error)
	usagelogFields := schema.UsageLog{}.Fields()
	_ = usagelogFields
	// usagelogDescRequestID is the schema descriptor for request_id field.
	usagelogDescRequestID := usagelogFields[4].Descriptor()
	// usagelog.RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	usagelog.RequestIDValidator = func() func(string) error {
		validators := usagelogDescRequestID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(request_id string) error {
			for _, fn := range fns {
				if err := fn(request_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usagelogDescModel is the schema descriptor for model field.
	usagelogDescModel := usagelogFields[5].Descriptor()
	// usagelog.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	usagelog.ModelValidator = func() func(string) error {
		validators := usagelogDescModel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(model string) error {
			for _, fn := range fns {
				if err := fn(model); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usagelogDescUpstreamModel is the schema descriptor for upstream_model field.
	usagelogDescUpstreamModel := usagelogFields[6].Descriptor()
	// usagelog.UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	usagelog.UpstreamModelValidator = usagelogDescUpstreamModel.Validators[0].(func(string) error)
	// usagelogDescInputTokens is the schema descriptor for input_tokens field.
	usagelogDescInputTokens := usagelogFields[7].Descriptor()
	// usagelog.DefaultInputTokens holds the default value on creation for the input_tokens field.
	usagelog.DefaultInputTokens = usagelogDescInputTokens.Default.(int)
	// usagelogDescOutputTokens is the schema descriptor for output_tokens field.
	usagelogDescOutputTokens := usagelogFields[8].Descriptor()
	// usagelog.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	usagelog.DefaultOutputTokens = usagelogDescOutputTokens.Default.(int)
	// usagelogDescCacheCreationTokens is the schema descriptor for cache_creation_tokens field.
	usagelogDescCacheCreationTokens := usagelogFields[9].Descriptor()
	// usagelog.DefaultCacheCreationTokens holds the default value on creation for the cache_creation_tokens field.
	usagelog.DefaultCacheCreationTokens = usagelogDescCacheCreationTokens.Default.(int)
	// usagelogDescCacheReadTokens is the schema descriptor for cache_read_tokens field.
	usagelogDescCacheReadTokens := usagelogFields[10].Descriptor()
	// usagelog.DefaultCacheReadTokens holds the default value on creation for the cache_read_tokens field.
	usagelog.DefaultCacheReadTokens = usagelogDescCacheReadTokens.Default.(int)
	// usagelogDescInputCost is the schema descriptor for input_cost field.
	usagelogDescInputCost := usagelogFields[11].Descriptor()
	// usagelog.DefaultInputCost holds the default value on creation for the input_cost field.
	usagelog.DefaultInputCost = usagelogDescInputCost.Default.(float64)
	// usagelogDescOutputCost is the schema descriptor for output_cost field.
	usagelogDescOutputCost := usagelogFields[12].Descriptor()
	// usagelog.DefaultOutputCost holds the default value on creation for the output_cost field.
	usagelog.DefaultOutputCost = usagelogDescOutputCost.Default.(float64)
	// usagelogDescTotalCost is the schema descriptor for total_cost field.
	usagelogDescTotalCost := usagelogFields[13].Descriptor()
	// usagelog.DefaultTotalCost holds the default value on creation for the total_cost field.
	usagelog.DefaultTotalCost = usagelogDescTotalCost.Default.(float64)
	// usagelogDescRateMultiplier is the schema descriptor for rate_multiplier field.
	usagelogDescRateMultiplier := usagelogFields[14].Descriptor()
	// usagelog.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	usagelog.DefaultRateMultiplier = usagelogDescRateMultiplier.Default.(float64)
	// usagelogDescStream is the schema descriptor for stream field.
	usagelogDescStream := usagelogFields[15].Descriptor()
	// usagelog.DefaultStream holds the default value on creation for the stream field.
	usagelog.DefaultStream = usagelogDescStream.Default.(bool)
	// usagelogDescStatusCode is the schema descriptor for status_code field.
	usagelogDescStatusCode := usagelogFields[18].Descriptor()
	// usagelog.DefaultStatusCode holds the default value on creation for the status_code field.
	usagelog.DefaultStatusCode = usagelogDescStatusCode.Default.(int)
	// usagelogDescUserAgent is the schema descriptor for user_agent field.
	usagelogDescUserAgent := usagelogFields[20].Descriptor()
	// usagelog.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	usagelog.UserAgentValidator = usagelogDescUserAgent.Validators[0].(func(string) error)
	// usagelogDescIPAddress is the schema descriptor for ip_address field.
	usagelogDescIPAddress := usagelogFields[21].Descriptor()
	// usagelog.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	usagelog.IPAddressValidator = usagelogDescIPAddress.Validators[0].(func(string) error)
	// usagelogDescCreatedAt is the schema descriptor for created_at field.
	usagelogDescCreatedAt := usagelogFields[22].Descriptor()
	// usagelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	usagelog.DefaultCreatedAt = usagelogDescCreatedAt.Default.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = func() func(string) error {
		validators := userDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_hash string) error {
			for _, fn := range fns {
				if err := fn(password_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[2].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[3].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// user.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	user.StatusValidator = userDescStatus.Validators[0].(func(string) error)
	// userDescNotes is the schema descriptor for notes field.
	userDescNotes := userFields[4].Descriptor()
	// user.DefaultNotes holds the default value on creation for the notes field.
	user.DefaultNotes = userDescNotes.Default.(string)
}
