// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "key", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "quota", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "quota_used", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "ip_whitelist", Type: field.TypeJSON, Nullable: true},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_groups_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[12]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[13]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_user_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[13]},
			},
			{
				Name:    "apikey_group_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[12]},
			},
			{
				Name:    "apikey_status",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[6]},
			},
			{
				Name:    "apikey_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[3]},
			},
			{
				Name:    "apikey_last_used_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[7]},
			},
		},
	}
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "platform", Type: field.TypeString, Size: 50, Default: "commandcode"},
		{Name: "type", Type: field.TypeString, Size: 20, Default: "apikey"},
		{Name: "credentials", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "extra", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "concurrency", Type: field.TypeInt, Default: 3},
		{Name: "priority", Type: field.TypeInt, Default: 50},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "error_message", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "schedulable", Type: field.TypeBool, Default: true},
		{Name: "rate_limited_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "rate_limit_reset_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "overload_until", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "balance_fetched_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "balance_error", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "balance_remaining", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "balance_plan_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "balance_period_end", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "balance_5h_used", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "balance_5h_cap", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "balance_5h_reset_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "balance_weekly_used", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "balance_weekly_cap", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "balance_weekly_reset_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "consecutive_failures", Type: field.TypeInt, Default: 0},
		{Name: "last_health_check_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "last_health_check_ok", Type: field.TypeBool, Default: false},
		{Name: "last_health_check_error", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "latency_ms", Type: field.TypeInt, Nullable: true},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "account_platform",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[6]},
			},
			{
				Name:    "account_status",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[13]},
			},
			{
				Name:    "account_schedulable",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[17]},
			},
			{
				Name:    "account_last_used_at",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[15]},
			},
			{
				Name:    "account_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[3]},
			},
			{
				Name:    "account_platform_priority",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[6], AccountsColumns[11]},
			},
			{
				Name:    "account_priority_status",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[11], AccountsColumns[13]},
			},
		},
	}
	// AccountGroupsColumns holds the columns for the "account_groups" table.
	AccountGroupsColumns = []*schema.Column{
		{Name: "priority", Type: field.TypeInt, Default: 50},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "account_id", Type: field.TypeInt64},
		{Name: "group_id", Type: field.TypeInt64},
	}
	// AccountGroupsTable holds the schema information for the "account_groups" table.
	AccountGroupsTable = &schema.Table{
		Name:       "account_groups",
		Columns:    AccountGroupsColumns,
		PrimaryKey: []*schema.Column{AccountGroupsColumns[2], AccountGroupsColumns[3]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "account_groups_accounts_account",
				Columns:    []*schema.Column{AccountGroupsColumns[2]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "account_groups_groups_group",
				Columns:    []*schema.Column{AccountGroupsColumns[3]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "accountgroup_group_id",
				Unique:  false,
				Columns: []*schema.Column{AccountGroupsColumns[3]},
			},
			{
				Name:    "accountgroup_priority",
				Unique:  false,
				Columns: []*schema.Column{AccountGroupsColumns[0]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "description", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "platform", Type: field.TypeString, Size: 50, Default: "commandcode"},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "group_status",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[8]},
			},
			{
				Name:    "group_platform",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[6]},
			},
			{
				Name:    "group_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[3]},
			},
		},
	}
	// UsageLogsColumns holds the columns for the "usage_logs" table.
	UsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "request_id", Type: field.TypeString, Size: 64},
		{Name: "model", Type: field.TypeString, Size: 100},
		{Name: "upstream_model", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_creation_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_read_tokens", Type: field.TypeInt, Default: 0},
		{Name: "input_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "output_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "total_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "duration_ms", Type: field.TypeInt, Nullable: true},
		{Name: "first_token_ms", Type: field.TypeInt, Nullable: true},
		{Name: "status_code", Type: field.TypeInt, Default: 200},
		{Name: "error_message", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "user_agent", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "ip_address", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "api_key_id", Type: field.TypeInt64},
		{Name: "account_id", Type: field.TypeInt64},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// UsageLogsTable holds the schema information for the "usage_logs" table.
	UsageLogsTable = &schema.Table{
		Name:       "usage_logs",
		Columns:    UsageLogsColumns,
		PrimaryKey: []*schema.Column{UsageLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "usage_logs_api_keys_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[20]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "usage_logs_accounts_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[21]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "usage_logs_groups_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[22]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_users_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[23]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usagelog_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[19]},
			},
			{
				Name:    "usagelog_model",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[2]},
			},
			{
				Name:    "usagelog_request_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[1]},
			},
			{
				Name:    "usagelog_account_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[21]},
			},
			{
				Name:    "usagelog_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[23], UsageLogsColumns[19]},
			},
			{
				Name:    "usagelog_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[20], UsageLogsColumns[19]},
			},
			{
				Name:    "usagelog_account_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[21], UsageLogsColumns[19]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "password_hash", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeString, Size: 20, Default: "user"},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "notes", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[7]},
			},
			{
				Name:    "user_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		AccountsTable,
		AccountGroupsTable,
		GroupsTable,
		UsageLogsTable,
		UsersTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = GroupsTable
	APIKeysTable.ForeignKeys[1].RefTable = UsersTable
	APIKeysTable.Annotation = &entsql.Annotation{
		Table: "api_keys",
	}
	AccountsTable.Annotation = &entsql.Annotation{
		Table: "accounts",
	}
	AccountGroupsTable.ForeignKeys[0].RefTable = AccountsTable
	AccountGroupsTable.ForeignKeys[1].RefTable = GroupsTable
	AccountGroupsTable.Annotation = &entsql.Annotation{
		Table: "account_groups",
	}
	GroupsTable.Annotation = &entsql.Annotation{
		Table: "groups",
	}
	UsageLogsTable.ForeignKeys[0].RefTable = APIKeysTable
	UsageLogsTable.ForeignKeys[1].RefTable = AccountsTable
	UsageLogsTable.ForeignKeys[2].RefTable = GroupsTable
	UsageLogsTable.ForeignKeys[3].RefTable = UsersTable
	UsageLogsTable.Annotation = &entsql.Annotation{
		Table: "usage_logs",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
