// Code generated by ent, DO NOT EDIT.

package account

import (
	"cmd2api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldName, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldNotes, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldPlatform, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldType, v))
}

// Concurrency applies equality check predicate on the "concurrency" field. It's identical to ConcurrencyEQ.
func Concurrency(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldConcurrency, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldPriority, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldRateMultiplier, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldStatus, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldErrorMessage, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLastUsedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldExpiresAt, v))
}

// Schedulable applies equality check predicate on the "schedulable" field. It's identical to SchedulableEQ.
func Schedulable(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSchedulable, v))
}

// RateLimitedAt applies equality check predicate on the "rate_limited_at" field. It's identical to RateLimitedAtEQ.
func RateLimitedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldRateLimitedAt, v))
}

// RateLimitResetAt applies equality check predicate on the "rate_limit_reset_at" field. It's identical to RateLimitResetAtEQ.
func RateLimitResetAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldRateLimitResetAt, v))
}

// OverloadUntil applies equality check predicate on the "overload_until" field. It's identical to OverloadUntilEQ.
func OverloadUntil(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldOverloadUntil, v))
}

// ConsecutiveFailures applies equality check predicate on the "consecutive_failures" field. It's identical to ConsecutiveFailuresEQ.
func ConsecutiveFailures(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// LastHealthCheckAt applies equality check predicate on the "last_health_check_at" field. It's identical to LastHealthCheckAtEQ.
func LastHealthCheckAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLastHealthCheckAt, v))
}

// LastHealthCheckOk applies equality check predicate on the "last_health_check_ok" field. It's identical to LastHealthCheckOkEQ.
func LastHealthCheckOk(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLastHealthCheckOk, v))
}

// LastHealthCheckError applies equality check predicate on the "last_health_check_error" field. It's identical to LastHealthCheckErrorEQ.
func LastHealthCheckError(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLastHealthCheckError, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLatencyMs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldName, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldNotes, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldPlatform, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldType, v))
}

// ConcurrencyEQ applies the EQ predicate on the "concurrency" field.
func ConcurrencyEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldConcurrency, v))
}

// ConcurrencyNEQ applies the NEQ predicate on the "concurrency" field.
func ConcurrencyNEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldConcurrency, v))
}

// ConcurrencyIn applies the In predicate on the "concurrency" field.
func ConcurrencyIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldConcurrency, vs...))
}

// ConcurrencyNotIn applies the NotIn predicate on the "concurrency" field.
func ConcurrencyNotIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldConcurrency, vs...))
}

// ConcurrencyGT applies the GT predicate on the "concurrency" field.
func ConcurrencyGT(v int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldConcurrency, v))
}

// ConcurrencyGTE applies the GTE predicate on the "concurrency" field.
func ConcurrencyGTE(v int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldConcurrency, v))
}

// ConcurrencyLT applies the LT predicate on the "concurrency" field.
func ConcurrencyLT(v int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldConcurrency, v))
}

// ConcurrencyLTE applies the LTE predicate on the "concurrency" field.
func ConcurrencyLTE(v int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldConcurrency, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldPriority, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldRateMultiplier, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldErrorMessage, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldLastUsedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldExpiresAt))
}

// SchedulableEQ applies the EQ predicate on the "schedulable" field.
func SchedulableEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSchedulable, v))
}

// SchedulableNEQ applies the NEQ predicate on the "schedulable" field.
func SchedulableNEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldSchedulable, v))
}

// RateLimitedAtEQ applies the EQ predicate on the "rate_limited_at" field.
func RateLimitedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldRateLimitedAt, v))
}

// RateLimitedAtNEQ applies the NEQ predicate on the "rate_limited_at" field.
func RateLimitedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldRateLimitedAt, v))
}

// RateLimitedAtIn applies the In predicate on the "rate_limited_at" field.
func RateLimitedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldRateLimitedAt, vs...))
}

// RateLimitedAtNotIn applies the NotIn predicate on the "rate_limited_at" field.
func RateLimitedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldRateLimitedAt, vs...))
}

// RateLimitedAtGT applies the GT predicate on the "rate_limited_at" field.
func RateLimitedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldRateLimitedAt, v))
}

// RateLimitedAtGTE applies the GTE predicate on the "rate_limited_at" field.
func RateLimitedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldRateLimitedAt, v))
}

// RateLimitedAtLT applies the LT predicate on the "rate_limited_at" field.
func RateLimitedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldRateLimitedAt, v))
}

// RateLimitedAtLTE applies the LTE predicate on the "rate_limited_at" field.
func RateLimitedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldRateLimitedAt, v))
}

// RateLimitedAtIsNil applies the IsNil predicate on the "rate_limited_at" field.
func RateLimitedAtIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldRateLimitedAt))
}

// RateLimitedAtNotNil applies the NotNil predicate on the "rate_limited_at" field.
func RateLimitedAtNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldRateLimitedAt))
}

// RateLimitResetAtEQ applies the EQ predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldRateLimitResetAt, v))
}

// RateLimitResetAtNEQ applies the NEQ predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldRateLimitResetAt, v))
}

// RateLimitResetAtIn applies the In predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldRateLimitResetAt, vs...))
}

// RateLimitResetAtNotIn applies the NotIn predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldRateLimitResetAt, vs...))
}

// RateLimitResetAtGT applies the GT predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldRateLimitResetAt, v))
}

// RateLimitResetAtGTE applies the GTE predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldRateLimitResetAt, v))
}

// RateLimitResetAtLT applies the LT predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldRateLimitResetAt, v))
}

// RateLimitResetAtLTE applies the LTE predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldRateLimitResetAt, v))
}

// RateLimitResetAtIsNil applies the IsNil predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldRateLimitResetAt))
}

// RateLimitResetAtNotNil applies the NotNil predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldRateLimitResetAt))
}

// OverloadUntilEQ applies the EQ predicate on the "overload_until" field.
func OverloadUntilEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldOverloadUntil, v))
}

// OverloadUntilNEQ applies the NEQ predicate on the "overload_until" field.
func OverloadUntilNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldOverloadUntil, v))
}

// OverloadUntilIn applies the In predicate on the "overload_until" field.
func OverloadUntilIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldOverloadUntil, vs...))
}

// OverloadUntilNotIn applies the NotIn predicate on the "overload_until" field.
func OverloadUntilNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldOverloadUntil, vs...))
}

// OverloadUntilGT applies the GT predicate on the "overload_until" field.
func OverloadUntilGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldOverloadUntil, v))
}

// OverloadUntilGTE applies the GTE predicate on the "overload_until" field.
func OverloadUntilGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldOverloadUntil, v))
}

// OverloadUntilLT applies the LT predicate on the "overload_until" field.
func OverloadUntilLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldOverloadUntil, v))
}

// OverloadUntilLTE applies the LTE predicate on the "overload_until" field.
func OverloadUntilLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldOverloadUntil, v))
}

// OverloadUntilIsNil applies the IsNil predicate on the "overload_until" field.
func OverloadUntilIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldOverloadUntil))
}

// OverloadUntilNotNil applies the NotNil predicate on the "overload_until" field.
func OverloadUntilNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldOverloadUntil))
}

// ConsecutiveFailuresEQ applies the EQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresNEQ applies the NEQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresIn applies the In predicate on the "consecutive_failures" field.
func ConsecutiveFailuresIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresNotIn applies the NotIn predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNotIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresGT applies the GT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGT(v int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresGTE applies the GTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGTE(v int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLT applies the LT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLT(v int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLTE applies the LTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLTE(v int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldConsecutiveFailures, v))
}

// LastHealthCheckAtEQ applies the EQ predicate on the "last_health_check_at" field.
func LastHealthCheckAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLastHealthCheckAt, v))
}

// LastHealthCheckAtNEQ applies the NEQ predicate on the "last_health_check_at" field.
func LastHealthCheckAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldLastHealthCheckAt, v))
}

// LastHealthCheckAtIn applies the In predicate on the "last_health_check_at" field.
func LastHealthCheckAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldLastHealthCheckAt, vs...))
}

// LastHealthCheckAtNotIn applies the NotIn predicate on the "last_health_check_at" field.
func LastHealthCheckAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldLastHealthCheckAt, vs...))
}

// LastHealthCheckAtGT applies the GT predicate on the "last_health_check_at" field.
func LastHealthCheckAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldLastHealthCheckAt, v))
}

// LastHealthCheckAtGTE applies the GTE predicate on the "last_health_check_at" field.
func LastHealthCheckAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldLastHealthCheckAt, v))
}

// LastHealthCheckAtLT applies the LT predicate on the "last_health_check_at" field.
func LastHealthCheckAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldLastHealthCheckAt, v))
}

// LastHealthCheckAtLTE applies the LTE predicate on the "last_health_check_at" field.
func LastHealthCheckAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldLastHealthCheckAt, v))
}

// LastHealthCheckAtIsNil applies the IsNil predicate on the "last_health_check_at" field.
func LastHealthCheckAtIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldLastHealthCheckAt))
}

// LastHealthCheckAtNotNil applies the NotNil predicate on the "last_health_check_at" field.
func LastHealthCheckAtNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldLastHealthCheckAt))
}

// LastHealthCheckOkEQ applies the EQ predicate on the "last_health_check_ok" field.
func LastHealthCheckOkEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLastHealthCheckOk, v))
}

// LastHealthCheckOkNEQ applies the NEQ predicate on the "last_health_check_ok" field.
func LastHealthCheckOkNEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldLastHealthCheckOk, v))
}

// LastHealthCheckErrorEQ applies the EQ predicate on the "last_health_check_error" field.
func LastHealthCheckErrorEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLastHealthCheckError, v))
}

// LastHealthCheckErrorNEQ applies the NEQ predicate on the "last_health_check_error" field.
func LastHealthCheckErrorNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldLastHealthCheckError, v))
}

// LastHealthCheckErrorIn applies the In predicate on the "last_health_check_error" field.
func LastHealthCheckErrorIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldLastHealthCheckError, vs...))
}

// LastHealthCheckErrorNotIn applies the NotIn predicate on the "last_health_check_error" field.
func LastHealthCheckErrorNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldLastHealthCheckError, vs...))
}

// LastHealthCheckErrorGT applies the GT predicate on the "last_health_check_error" field.
func LastHealthCheckErrorGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldLastHealthCheckError, v))
}

// LastHealthCheckErrorGTE applies the GTE predicate on the "last_health_check_error" field.
func LastHealthCheckErrorGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldLastHealthCheckError, v))
}

// LastHealthCheckErrorLT applies the LT predicate on the "last_health_check_error" field.
func LastHealthCheckErrorLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldLastHealthCheckError, v))
}

// LastHealthCheckErrorLTE applies the LTE predicate on the "last_health_check_error" field.
func LastHealthCheckErrorLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldLastHealthCheckError, v))
}

// LastHealthCheckErrorContains applies the Contains predicate on the "last_health_check_error" field.
func LastHealthCheckErrorContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldLastHealthCheckError, v))
}

// LastHealthCheckErrorHasPrefix applies the HasPrefix predicate on the "last_health_check_error" field.
func LastHealthCheckErrorHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldLastHealthCheckError, v))
}

// LastHealthCheckErrorHasSuffix applies the HasSuffix predicate on the "last_health_check_error" field.
func LastHealthCheckErrorHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldLastHealthCheckError, v))
}

// LastHealthCheckErrorIsNil applies the IsNil predicate on the "last_health_check_error" field.
func LastHealthCheckErrorIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldLastHealthCheckError))
}

// LastHealthCheckErrorNotNil applies the NotNil predicate on the "last_health_check_error" field.
func LastHealthCheckErrorNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldLastHealthCheckError))
}

// LastHealthCheckErrorEqualFold applies the EqualFold predicate on the "last_health_check_error" field.
func LastHealthCheckErrorEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldLastHealthCheckError, v))
}

// LastHealthCheckErrorContainsFold applies the ContainsFold predicate on the "last_health_check_error" field.
func LastHealthCheckErrorContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldLastHealthCheckError, v))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldLatencyMs, v))
}

// LatencyMsIsNil applies the IsNil predicate on the "latency_ms" field.
func LatencyMsIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldLatencyMs))
}

// LatencyMsNotNil applies the NotNil predicate on the "latency_ms" field.
func LatencyMsNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldLatencyMs))
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, GroupsTable, GroupsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.Group) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccountGroups applies the HasEdge predicate on the "account_groups" edge.
func HasAccountGroups() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, AccountGroupsTable, AccountGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountGroupsWith applies the HasEdge predicate on the "account_groups" edge with a given conditions (other predicates).
func HasAccountGroupsWith(preds ...predicate.AccountGroup) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newAccountGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Account) predicate.Account {
	return predicate.Account(sql.NotPredicates(p))
}
